name: build docker image

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "davidlblanco" --password-stdin

      - name: Set Docker image tag and environment variables
        id: vars
        run: |
          echo "IMAGE_TAG=school-blog-back:$(date +%s)" >> $GITHUB_ENV
          echo "PSQL_URL=${{ secrets.PSQL_URL }}" >> $GITHUB_ENV
          echo "WT_SECRET=${{ secrets.WT_SECRET }}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build -f Dockerfile-git -t davidlblanco/${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to Docker Hub
        run: docker push davidlblanco/${{ env.IMAGE_TAG }}
#  docker build -t davidlblanco/school-blog-back:test .
# docker push davidlblanco/school-blog-back:test

