name: build docker image

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "davidlblanco" --password-stdin

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag school-blog-back:$(date +%s)

      - name: Tag Docker Image
        run: docker tag school-blog-back:$(date +%s) davidlblanco/school-blog-back:latest

      - name: Push Docker Image to Docker Hub
        run: docker push davidlblanco/school-blog-back:latest
